#!/bin/sh

find . -type f -name '*.gif' -print0 |
while IFS= read -r -d '' file; do
    filename="${file##*/}"           
    name="${filename%.gif}"          
    printf "%s\n" "$name"
done |
LC_ALL=C sort -f

